# Copyright (c) 2026 Ravenkey LLC. All rights reserved.
TOPICS = {
    "ovc": {
        "name": "OVC Compliance",
        "description": "Office for Victims of Crime — grant guidelines, VOCA requirements, tribal victim services set-aside, victim compensation, and compliance updates.",
        "icon": "♥",
        "tier": 1,
    },
    "doj-grants": {
        "name": "DOJ Grants",
        "description": "BJA, OJJDP, NIJ, COPS — grant opportunities, program guidelines, award announcements, and compliance reporting.",
        "icon": "◆",
        "tier": 1,
    },
    "federal-register": {
        "name": "Federal Register",
        "description": "Agency rules, proposed regulations, public comment periods, and final rules affecting federal grants and compliance.",
        "icon": "⚖",
        "tier": 1,
    },
    "tribal-funding": {
        "name": "Tribal Funding",
        "description": "IHS, HUD/NAHASDA, BIA, EPA IGAP — tribal-specific grant programs, allocations, compliance requirements, and deadlines.",
        "icon": "♦",
        "tier": 1,
    },
    "grant-regulations": {
        "name": "Grant Regulations",
        "description": "OMB circulars, 2 CFR 200, Uniform Guidance changes, Single Audit requirements, and grant management standards.",
        "icon": "■",
        "tier": 1,
    },
    "grant-opportunities": {
        "name": "Grant Opportunities",
        "description": "New federal grant announcements across all relevant agencies — open opportunities, pre-applications, and forecasted grants.",
        "icon": "●",
        "tier": 2,
    },
    "compliance-deadlines": {
        "name": "Compliance Deadlines",
        "description": "Grant application deadlines, reporting due dates, audit deadlines, and compliance milestones.",
        "icon": "▲",
        "tier": 2,
    },
    "hhs-grants": {
        "name": "HHS Grants",
        "description": "ACF, SAMHSA, HRSA — grant programs for health services, substance abuse treatment, and community programs.",
        "icon": "♥",
        "tier": 2,
    },
    "hud-grants": {
        "name": "HUD Grants",
        "description": "CDBG, HOME, IHBG, Indian Housing Block Grant — housing and community development grant programs.",
        "icon": "■",
        "tier": 2,
    },
}

TOPIC_BY_CATEGORY = {
    "OVCCompliance": "ovc",
    "VictimServices": "ovc",
    "VOCA": "ovc",
    "TribalVictim": "ovc",
    "BJA": "doj-grants",
    "OJJDP": "doj-grants",
    "NIJ": "doj-grants",
    "COPS": "doj-grants",
    "DOJGrants": "doj-grants",
    "AgencyRules": "federal-register",
    "ProposedRules": "federal-register",
    "PublicComment": "federal-register",
    "FinalRules": "federal-register",
    "IHS": "tribal-funding",
    "NAHASDA": "tribal-funding",
    "BIA": "tribal-funding",
    "EPAIGAP": "tribal-funding",
    "TribalHealth": "tribal-funding",
    "OMB": "grant-regulations",
    "UniformGuidance": "grant-regulations",
    "SingleAudit": "grant-regulations",
    "2CFR200": "grant-regulations",
    "NewGrants": "grant-opportunities",
    "OpenOpportunities": "grant-opportunities",
    "ForecastGrants": "grant-opportunities",
    "Deadlines": "compliance-deadlines",
    "ReportingDates": "compliance-deadlines",
    "AuditDeadlines": "compliance-deadlines",
    "ACF": "hhs-grants",
    "SAMHSA": "hhs-grants",
    "HRSA": "hhs-grants",
    "HealthGrants": "hhs-grants",
    "CDBG": "hud-grants",
    "HOME": "hud-grants",
    "IHBG": "hud-grants",
    "HousingGrants": "hud-grants",
}
